image: nberlette/gitpod-enhanced:latest

tasks:
  - init: |
      if ! command -v deno &>/dev/null; then
        curl -fsSL https://deno.land/install.sh | sh -;
        deno upgrade --canary -q -f 
      fi
      if [ -r ./deno.lock ]; then
        rm -f deno.lock &>/dev/null;
        for f in $(find . -type f \( -name "*.ts" -or -name "*.mjs" -or -name "*.js" \) -maxdepth 3 \;); do 
          deno cache --reload --lock-write "$f" &>/dev/null; 
        done
      fi
    command: |
      if [ -r ./deno.json ] || [ -r ./deno.jsonc ]; then
        deno task dev 2>/dev/null || deno task
      fi

vscode:
  extensions:
    - denoland.vscode-deno
    - editorconfig.editorconfig
    - vsls-contrib.gistfs
    - redhat.vscode-yaml
    - gitpod.gitpod-desktop
    - gitpod.gitpod-remote-ssh
    - akosyakov.gitpod-monitor
    - github.copilot
    - github.copilot-labs
    - github.vscode-pull-request-github


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addLabel: "gitpod"
    addCheck: "prevent-merge-on-error"
    addBadge: true

ports:
  - port: 8000-8888
    visibility: private
    onOpen: open-preview
